logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    root: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(xLpZHMkrTuqdT9NkmttvVeOPD+n4pgnCXBEGdv7CDo8ebW4jpPr2jfun6qUjmHGIQUjBPKl9D7ZPLsatvBvH6MdhFZDOfRhrT/J9N9ONMBHdDGMq3uy1UQ==)
    username: ENC(vrL9TwKqOlu/MWgi9xLopg==)
    password: ENC(s8y1RE5McsBd7bXnjiOqmjUM7pZOFahF)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ENC(BqGp9KuA0J/mD+gICtrtGB47pb2caohYXo9LQYt9Qmo=)
    password: ENC(ShJVYZYLqhAbls2M80xQsuXtTYnpPUEWAkKncu7TqZU=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
          debug: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(HDRxoK2qiQWSkdiJX/FbJAcoB74kpAKX)
      expiration.time: 300

coolsms:
  api:
    key: ENC(8OPB69vC8GJP+53rwqNDLTlDMY+qD5tx7SELupzw6QU=)
    secret: ENC(JBe/BbCbF2g+piCNr3cAlItyyVYsX1qDw3ZSB9nVDh28sJECSIx/X3bimj2AkKmn)
    from: ENC(LckUTxvkdVjS8cyVgAoHRBBA/6Ep2CgD)
    domain: https://api.coolsms.co.kr

jasypt.encryptor.password: ${ENCRYPT_KEY}