logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(xLpZHMkrTuqdT9NkmttvVeOPD+n4pgnCXBEGdv7CDo8ebW4jpPr2jfun6qUjmHGIQUjBPKl9D7ZPLsatvBvH6MdhFZDOfRhrT/J9N9ONMBHdDGMq3uy1UQ==)
    username: ENC(vrL9TwKqOlu/MWgi9xLopg==)
    password: ENC(s8y1RE5McsBd7bXnjiOqmjUM7pZOFahF)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ENC(BqGp9KuA0J/mD+gICtrtGB47pb2caohYXo9LQYt9Qmo=)
    password: ENC(ShJVYZYLqhAbls2M80xQsuXtTYnpPUEWAkKncu7TqZU=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
          debug: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(HDRxoK2qiQWSkdiJX/FbJAcoB74kpAKX)
      expiration.time: 300

coolsms:
  api:
    key: ENC(8OPB69vC8GJP+53rwqNDLTlDMY+qD5tx7SELupzw6QU=)
    secret: ENC(JBe/BbCbF2g+piCNr3cAlItyyVYsX1qDw3ZSB9nVDh28sJECSIx/X3bimj2AkKmn)
    from: ENC(LckUTxvkdVjS8cyVgAoHRBBA/6Ep2CgD)
    domain: https://api.coolsms.co.kr

codef:
  sandbox:
    client-id: ef27cfaa-10c1-4470-adac-60ba476273f9
    client-secret: 83160c33-9045-4915-86d8-809473cdf5c3
    public-key: ENC(Fv8Q7iP9rYnLMLywBEIucONbFVVIpfMbtjMJrQmc+D3LWQ2XUfpjcE2j8UYDU2MT/YpX5Mb2CfJY8/0e22BP1xos3DWEVVHi3kovkmTPvmdd1oc2Zn+92Um4Z+OmJB3xpepkp3SwEr9zbdliyS3/nlk8yojWyrzhjKmsJAcpjrcjA0lTRjR/gk8hrTsa25byAgWn552B02lez4k3fh2wMZSYgmhFSBcYiC9jdT2jjRJiMDFbsnq/V9jRj379abB095yilfh3eV/ZmTO+8EF922kxr2HCyNHfNIf7jTwrxTmfw/gRBZhAbaR8rVgNgKwwPYhLDWZGZreCNR4hCTR6oD9gG51PDoizsaqsWJr+G4IJRayoCl5OfYeWqRX4zLCWAEGfqqh1rP8LZqLUAKNAXrcTLJ3S5eycXkjyv4CTvLWQPDfbJpNelu7O0KgcmCBlCoR/1uE9L5PdkRDzW4xaRyMCtkt/FvLpzS3J9zaDeYRc0jOvDjTa9OFh/90QyZlCYxNp7yD96nUWy2FxV39dRFmjsAsCaBO6)

jasypt.encryptor.password: ${ENCRYPT_KEY}